fullnameOverride: "tempo"
multitenancyEnabled: true

tempo:
  auth_enabled: false

storage:
  trace:
    backend: azure
    azure:
      storage_account_name: lgtmstoragejarvis
      account_key: "<AZURE_STORAGE_ACCOUNT_KEY>"
      container_name: tempo-traces

traces:
  otlp:
    grpc:
      enabled: true
    http:
      enabled: true

minio:
  enabled: false
rollout_operator:
  enabled: false
memcached:
  enabled: false
metricsGenerator:
  enabled: false

ingester:
  replicas: 1
  zoneAwareReplication:
    enabled: false
  persistence:
    enabled: false
  podDisruptionBudget:
    enabled: false
  config:
    replication_factor: 1

distributor:
  replicas: 1
  podDisruptionBudget:
    enabled: false

compactor:
  replicas: 1
  podDisruptionBudget:
    enabled: false

querier:
  replicas: 1
  podDisruptionBudget:
    enabled: false

queryFrontend:
  replicas: 1
  podDisruptionBudget:
    enabled: false
